services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - auth-service
      - chat-service
      - mongodb
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - skuggsnack-network

  auth-service:
    build: ./auth-service
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/skuggsnack
      - PORT=9000
      - SECRET_KEY=amFnaGFyZW5qw6R2bGFtYXNzYW55Y2tsYXJpY2xlYXJ0ZXh0cMOlbWluc2VydmVy
      - AUTH_SERVICE_URL=http://auth-service:9000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - skuggsnack-network

  chat-service:
    build: ./chat-service
    ports:
      - "9001:9001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/skuggsnack
      - PORT=9000
      - SECRET_KEY=amFnaGFyZW5qw6R2bGFtYXNzYW55Y2tsYXJpY2xlYXJ0ZXh0cMOlbWluc2VydmVy
      - AUTH_SERVICE_URL=http://auth-service:9000
    networks:
      - skuggsnack-network

  mongodb:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - skuggsnack-network
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  skuggsnack-network:
    driver: bridge

volumes:
  mongo-data:
