# docker-compose.yml

version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - auth-service
      - chat-service
      - mongodb
    networks:
      - skuggsnack-network

  auth-service:
    build: ./auth-service
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/skuggsnack
      - SECRET_KEY=amFnaGFyZW5qw6R2bGFtYXNzYW55Y2tsYXJpY2xlYXJ0ZXh0cMOlbWluc2VydmVy
    networks:
      - skuggsnack-network

  chat-service:
    build: ./chat-service
    ports:
      - "9001:9001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/skuggsnack
    networks:
      - skuggsnack-network

  mongodb:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - skuggsnack-network

networks:
  skuggsnack-network:
    driver: bridge

volumes:
  mongo-data:
