apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: skuggsnack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      containers:
      - name: auth-service
        image: edvinem/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/skuggsnack
        - name: PORT
          value: "9000"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: secret_key
