apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: skuggsnack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: edvinem/chat-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/skuggsnack
        - name: PORT
          value: "9001"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: secret_key
